version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Costa_Rica
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code.terra1.terralabs.tk #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /home/terra/code-server:/config
    ports:
      - 8443:8443
    restart: unless-stopped
